# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RAPgaGKD70t_2heXSx3JbgzZe0d2B_Og
"""

import sklearn
import numpy as np
import pandas as pd
df=pd.read_csv("/train.csv")

data=df[["LotArea","SalePrice","GrLivArea","TotalBsmtSF","GarageArea"]]
var_predict="SalePrice"
X=np.array(data.drop([var_predict],1))
y=np.array(data[var_predict])

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=linear_model.LinearRegression()
model.fit(x_train,y_train)

print(model.coef_)

print(model.score(x_test,y_test))

p=model.predict(x_test)

for i in range (len(p)):
  print(p[i],x_test[i],y_test[i])